#!/bin/bash

DOCS_ROOT="$HOME/Documents/Obsidian Vault/Docusaurus"
echo "Rsyncing Obsidian notes to Docusaurus docs directory..."
rsync -av "$DOCS_ROOT/" "./docs/"
echo "Pushing changes to GitHub repository..."
git add "docs/$DIR"
if ! git commit -m "Notes synced from Obsidian" &>/dev/null; then
  echo "No changes to commit."
else
  git push origin main
fi

echo "Building and deploying Docusaurus site..."
npm run build
USE_SSH=true npm run deploy
